# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    uploads_directory: '%kernel.root_dir%/../web/uploads/images'
    main_image_directory: 'main_images'

services:
    faplike.service.image_uploader:
        class: AppBundle\Service\ImageUploader
        arguments: ['%uploads_directory%']

    faplike.service.person_predictor:
        class: AppBundle\Service\PersonPredictor
        arguments: ['%uploads_directory%']

    faplike.service.image_from_url:
        class: AppBundle\Service\ImageFromUrl

    faplike.service.video_api:
        class: AppBundle\Service\VideoAPI

    faplike.repository.main_image:
        class: AppBundle\Repository\MainImage
        arguments: ['%main_image_directory%']
