# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    images_directory: '%kernel.root_dir%/../web/uploads/images'

services:
    dopplerganger.image_uploader:
        class: AppBundle\Service\ImageUploader
        arguments: ['%images_directory%']
